site_name: 以太坊文档
site_description: 以太坊中文文档
site_author: Nosy
copyright: '版权 &copy; 2018 -  wohugb.github.io'

repo_name: wohugb/ethereum-docs
repo_url: https://github.com/wohugb/ethereum-docs
edit_uri: ""

theme:
  name: material

  include_search_page: false
  search_index_only: true

  language: zh
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
  extra_css: [assets/stylesheets/extra.css]
extra:
  social:
    - type: globe
      link: http://wohugb.github.io
    - type: github-alt
      link: https://github.com/wohugb
    - type: twitter
      link: https://twitter.com/wohugb
    - type: linkedin
      link: https://linkedin.com/in/wohugb

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      # provider
      # user
      # repo
      # labels
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.progressbar:
      level_class: true

pages:
  - 前言: index.md
  - 概述: home.md
  - 基础:
    - 介绍: Basics/introduction.md
    - 获取以太: Basics/Getting-Ether.md
    - 无心应用: Basics/dapps.md
    - 设计原理: Basics/Design-Rationale.md
    - 黄皮书: Yellow-Paper/index.md
    - FAQ: Basics/FAQ.md
    - 发布: Basics/Releases.md
    - 愿望清单: Basics/Wishlist.md
  - 白皮书:
    - 概述: White-Paper/index.md
    - 历史: White-Paper/history.md
    - 以太坊: White-Paper/Ethereum.md
    - 应用: White-Paper/Applications.md
    - 杂项: White-Paper/Miscellanea-And-Concerns.md
    - 结论: White-Paper/Conclusion.md
    - 更多: White-Paper/Notes-and-Further-Reading.md
  - 客户端:
    - 概述: Clients/index.md
    - Geth (Go): 
      - 简介: Clients/go-ethereum.md
      - 首页: Clients/geth/index.md
      - 安装: Clients/geth/Building-Ethereum.md
    - Parity (Rust): Clients/parity.md
    - pyethapp (Python): Clients/pyethapp.md
    - cpp-ethereum (C++): Clients/cpp-ethereum.md
    - ethereumj (Java): Clients/ethereumj.md
  - ÐApp开发:
    - 安全技术: Dapps/Safety.md
    - 开发资源: Dapps/Resources.md
    - JS API: Dapps/JavaScript-API.md
    - JSON RPC API: Dapps/JSON-RPC.md
    - Solidity: Dapps/solidity.md
    - Solidity 特色: Dapps/Solidity-Features.md
    - Solidity 合集: Dapps/Solidity-Collections.md
    - Solidity 备忘单: Dapps/solidity-cheatsheet.md
    - 有用的Ðapp模式: Dapps/Useful-Ðapp-Patterns.md
    - 标准化合约接口: Dapps/Standardized_Contract_APIs.md
    - 使用Meteor: Dapps/Using-Meteor.md
    - 开发指南: Dapps/Tutorial.md
    - Mix 指南: Dapps/Mix-IDE.md
    - Mix 特色: Dapps/Mix-Features.md
    - Viper: Dapps/viper.md
    - Serpent: Dapps/Serpent.md
    - LLL: Dapps/LLL.md
    - Mutan: Dapps/mutan.md
  - 基础设施:
    - 链规范格式: Infrastructure/Chain-Spec-Format.md
    - 地址互换协议: Infrastructure/Inter-exchange-Client-Address-Protocol.md
    - 网址提示协议: Infrastructure/URL-Hint-Protocol.md
    - 自然规格确认: Infrastructure/NatSpec-Determination.md
    - 网络状态: Infrastructure/Network-Status.md
    - 树莓派: Infrastructure/Raspberry-Pi-instructions.md
    - 交易一体化: Infrastructure/Exchange-Integration.md
    - 挖矿: Infrastructure/Mining.md
    - 许可: Infrastructure/Licensing.md
    - 联盟链开发: Infrastructure/Consortium-Chain-Development.md
  - 研究:
    - 权益证明: Research/Proof-of-Stake-FAQ.md
    - 分片区块链: Research/Sharding-FAQ.md
  - ÐΞV技术:
    - RLP 编码: D3VTechnologies/RLP.md
    - 节点发现协议: D3VTechnologies/Node-discovery-protocol.md
    - ÐΞVp2p 有线协议: D3VTechnologies/Wire-Protocol.md
    - ÐΞVp2p 白皮书: D3VTechnologies/libp2p-Whitepaper.md
    - Web3 秘密存储: D3VTechnologies/Web3-Secret-Storage-Definition.md
  - 以太坊技术:
    - 词树: Technologies/Patricia-Tree.md
    - 有线协议: Technologies/Ethereum-Wire-Protocol.md
    - 轻端协议: Technologies/Light-client-protocol.md
    - 玄机: Technologies/Subtleties.md
    - 固语言: Technologies/Solidity.md
    - NatSpec格式: Technologies/Ethereum-Natural-Specification-Format.md
    - 合同ABI: Technologies/Ethereum-Contract-ABI.md
    - 坏块报告: Technologies/Bad-Block-Reporting.md
    - 坏链金丝雀: Technologies/Bad-Chain-Canary.md
  - 挖矿:
    - 概述: Miner/index.md
    - 挖矿: Miner/miner.md
    - Ethash: Miner/Ethash.md
    - Ethash C API: Miner/Ethash-C-API.md
    - Ethash DAG: Miner/Ethash-DAG.md
  - 私语:
    - 低语提议: Whisper/index.md
    - 耳语概述: Whisper/Overview.md
    - PoC-1 有线协议: Whisper/Wire-Protocol.md
    - PoC-2 有线协议: Whisper/PoC-2-Wire-Protocol.md
    - PoC-2 白皮书: Whisper/PoC-2-Protocol-Spec.md
  - 杂项:
    - 加密货币的难题: Misc/Problems.md
    - 链条纤维: Misc/Chain-Fibers-Redux.md
    - 词汇表: Misc/Glossary.md
